module BackendJasminBuiltins where

classNameMacro = "*CLASS_NAME*"

builtinMethods = [
    ".field public static input Ljava/io/InputStreamReader;",
    ".field public static reader Ljava/io/BufferedReader;",
    "",
    ".method <init>()V",
    "  .limit stack 1",
    "  .limit locals 1",
    "  .line 3",
    "  0: aload_0",
    "  1: invokespecial java/lang/Object/<init>()V",
    "  4: return",
    ".end method",
    "",
    ".method public static printInt(I)I",
    "  .limit stack 2",
    "  .limit locals 1",
    "  .line 7",
    "  0: getstatic java/lang/System/out Ljava/io/PrintStream;",
    "  3: iload_0",
    "  4: invokevirtual java/io/PrintStream/println(I)V",
    "  .line 8",
    "     iconst_0",
    "     ireturn",
    ".end method",
    "",
    ".method public static printString(Ljava/lang/String;)I",
    "  .limit stack 2",
    "  .limit locals 1",
    "  .line 10",
    "  0: getstatic java/lang/System/out Ljava/io/PrintStream;",
    "  3: aload_0",
    "  4: invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V",
    "  .line 11",
    "     iconst_0",
    "     ireturn",
    ".end method",
    "",
    ".method public static error()I",
    "  .limit stack 2",
    "  .limit locals 0",
    "  .line 13",
    "  0: getstatic java/lang/System/err Ljava/io/PrintStream;",
    "  3: ldc \"runtime error\"",
    "  5: invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V",
    "  .line 14",
    "  8: iconst_1",
    "  9: invokestatic java/lang/System/exit(I)V",
    "  .line 15",
    "     iconst_0",
    "     ireturn",
    ".end method",
    "",
    ".method public static readInt()I",
    "  .limit stack 1",
    "  .limit locals 2",
    "  .line 17",
    "  0: iconst_0",
    "  1: istore_0",
    "Label2:",
    "  .line 19",
    "  2: getstatic " ++ classNameMacro ++ "/reader Ljava/io/BufferedReader;",
    "  5: invokevirtual java/io/BufferedReader/readLine()Ljava/lang/String;",
    "  8: astore_1",
    "  .line 20",
    "  9: aload_1",
    "  10: invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I",
    "  13: istore_0",
    "Label14:",
    "  .line 21",
    "  14: goto Label18",
    "Label17:",
    "  17: astore_1",
    "Label18:",
    "  .line 22",
    "  18: iload_0",
    "  19: ireturn",
    "  .catch java/io/IOException from Label2 to Label14 using Label17",
    "  ; full_frame (frameNumber = 0)",
    "  ; frame_type = 255, offset_delta = 17",
    "  ; frame bytes: 255 0 17 0 1 1 0 1 7 0 39 ",
    "  .stack ",
    "    offset 17",
    "    locals Integer",
    "    stack Object java/io/IOException",
    "    .end stack",
    "  ; same_frame (frameNumber = 1)",
    "  ; frame_type = 0, offset_delta = 0",
    "  ; frame bytes: 0 ",
    "  .stack ",
    "    offset 18",
    "    locals Integer",
    "    .end stack",
    ".end method",
    "",
    ".method public static readString()Ljava/lang/String;",
    "  .limit stack 1",
    "  .limit locals 2",
    "  .line 25",
    "  0: ldc \"\"",
    "  2: astore_0",
    "Label3:",
    "  .line 27",
    "  3: getstatic " ++ classNameMacro ++ "/reader Ljava/io/BufferedReader;",
    "  6: invokevirtual java/io/BufferedReader/readLine()Ljava/lang/String;",
    "  9: astore_0",
    "Label10:",
    "  .line 28",
    "  10: goto Label14",
    "Label13:",
    "  13: astore_1",
    "Label14:",
    "  .line 29",
    "  14: aload_0",
    "  15: areturn",
    "  .catch java/io/IOException from Label3 to Label10 using Label13",
    "  ; full_frame (frameNumber = 0)",
    "  ; frame_type = 255, offset_delta = 13",
    "  ; frame bytes: 255 0 13 0 1 7 0 42 0 1 7 0 39 ",
    "  .stack ",
    "    offset 13",
    "    locals Object java/lang/String",
    "    stack Object java/io/IOException",
    "    .end stack",
    "  ; same_frame (frameNumber = 1)",
    "  ; frame_type = 0, offset_delta = 0",
    "  ; frame bytes: 0 ",
    "  .stack ",
    "    offset 14",
    "    locals Object java/lang/String",
    "    .end stack",
    ".end method",
    "",
    ".method public static strComp(Ljava/lang/String;Ljava/lang/String;)I",
    "  .limit stack 2",
    "  .limit locals 2",
    "  .line 32",
    "  0: aload_0",
    "  1: aload_1",
    "  2: invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z",
    "  5: ifeq Label10",
    "  8: iconst_1",
    "  9: ireturn",
    "Label10:",
    "  .line 33",
    "  10: iconst_0",
    "  11: ireturn",
    "  ; same_frame (frameNumber = 0)",
    "  ; frame_type = 10, offset_delta = 10",
    "  ; frame bytes: 10 ",
    "  .stack ",
    "    offset 10",
    "    .end stack",
    ".end method",
    "",
    ".method public static strConcat(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
    "  .limit stack 2",
    "  .limit locals 3",
    "  .line 36",
    "  0: aload_0",
    "  1: astore_2",
    "  .line 37",
    "  2: aload_2",
    "  3: aload_1",
    "  4: invokevirtual java/lang/String/concat(Ljava/lang/String;)Ljava/lang/String;",
    "  7: areturn",
    ".end method",
    "",
    ".method public static modulo(II)I",
    "  .limit stack 2",
    "  .limit locals 2",
    "  .line 41",
    "  0: iload_0",
    "  1: iload_1",
    "  2: irem",
    "  3: ireturn",
    ".end method",
    "",
    ".method static <clinit>()V",
    "  .limit stack 3",
    "  .limit locals 0",
    "  .line 4",
    "  0: new java/io/InputStreamReader",
    "  3: dup",
    "  4: getstatic java/lang/System/in Ljava/io/InputStream;",
    "  7: invokespecial java/io/InputStreamReader/<init>(Ljava/io/InputStream;)V",
    "  10: putstatic " ++ classNameMacro ++ "/input Ljava/io/InputStreamReader;",
    "  .line 5",
    "  13: new java/io/BufferedReader",
    "  16: dup",
    "  17: getstatic " ++ classNameMacro ++ "/input Ljava/io/InputStreamReader;",
    "  20: invokespecial java/io/BufferedReader/<init>(Ljava/io/Reader;)V",
    "  23: putstatic " ++ classNameMacro ++ "/reader Ljava/io/BufferedReader;",
    "  26: return",
    ".end method" ]
mainMethod = [
    ".method public static main([Ljava/lang/String;)V",
    ".limit locals 1",
    ".limit stack 2",
    "    invokestatic " ++ classNameMacro ++ "/main__()I",
    "    invokestatic java/lang/System/exit(I)V",
    "    return",
    ".end method"]
